# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whom', to='accounts.UserProfile'),
        ),
    ]
