# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170502_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='content',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
